---
title: "Final project"
author: "Your name goes here"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```

```{r load-libraries, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(lubridate)
library(here)
library(skimr)
library(janitor)
library(vroom)
library(tidyquant)
library(spotifyr)
library(lubridate)
library(scales)
library(patchwork)
```

```{r}
#loading data and fixing column names using janitor
spotify_data <- vroom("data/spotify.csv", show_col_types = FALSE) %>% 
  clean_names()

glimpse(spotify_data)
```

```{r}
summary(spotify_data)
```


```{r}
#check NA values for the release date
sum(is.na(spotify_data$`Release Date`))
```

```{r}
#clean data
spotify_data_clean <- spotify_data %>%
  dplyr::select(-index) %>%  #remove index column
  dplyr::select(-artist_followers,-streams, -song_id, everything()) %>%#move some not-so-important variables to the end. 
  mutate(
    release_date = mdy(release_date),#convert release date from char to date format
    release_month = month(release_date, label=TRUE, abbr = TRUE),
    release_day = day(release_date),
    duration_min = duration_ms / 60000
  ) %>%
  filter(!is.na(release_date))#17 values had a different format than month-day-year. We remove these and the previous NA values.

glimpse(spotify_data_clean)
```
```{r}
glimpse(monthly_distrib)
```

```{r}
# Looking at the distribution of songs per month

monthly_distrib <- spotify_data_clean %>%
  group_by(release_month) %>%
  summarize(
    count = n()
  ) 

monthly_distrib <- monthly_distrib %>%
  mutate(top3 = rank(-count) %in% 1:3)
  
ggplot(data = monthly_distrib) +
  aes(x = release_month, 
      y = count, 
      fill= top3) +
  geom_bar(stat = 'identity', width=0.8) + 
  labs(
    x = "Month of release",
    y = "Number of songs",
    title = "Most hits were released in March, May and June"
  ) +
  scale_fill_manual(values = c("TRUE" = "#1db954", "FALSE" = "light grey")) +
  theme_bw() + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.position="none")

day_distrib <- spotify_data_clean %>%
  group_by(release_day) %>%
  summarize(
    count = n()
  ) 

day_distrib <- day_distrib %>%
  mutate(top3 = rank(-count) %in% 1:3)

ggplot(data = day_distrib) + 
  aes(x = release_day, y = count, fill = top3) +
  geom_bar(stat = 'identity', width=0.8, aes(xmin=1)) + 
  labs(
    x = "Day of release",
    y = "",
    title = "Most hits were released on the 6th, 10th and 13th"
  ) +
  scale_fill_manual(values = c("TRUE" = "#1db954", "FALSE" = "light grey")) +
  coord_cartesian(xlim =c(1, 31)) +
  theme_bw() + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.position="none")

```
```{r}
#Relation between song popularity and duration

ggplot(data = spotify_data_clean) +
  aes(x = duration_min, y = popularity) +
  geom_point() +
  geom_smooth(color="#1db954", se=FALSE) +
  theme_bw() +
  labs(
    x = "Duration (in min)",
    y = "Popularity",
    title = "Most hits are between 2.5 to 3 minutes long"
  )


```

